### ISSUE TITLE
New topics in MARL?

### ISSUE THREAD

**Issue by qiaodan-cuhk** [LantaoYu/MARL-Papers#24]
Is there any new topic can be added into the paper list according to the taxonomy? Such as LLM-based MARL, generative model based MARL, & Game Theory  based theoretical analysis? I'm not sure what the hot topics in the community are since 2023

**Comment by chauncygu** [comment]
Hi qiaodan-cuhk,

Thanks a lot, we are adding more literature regarding LLMs in the repository.

Thanks!
